### ISSUE TITLE
Issue running shiny app

### ISSUE THREAD

**Issue by cavargasru** [bertozzivill/map-itn-cube#208]
Hi @bertozzivill,

When trying to run the shiny app I got:

 Error in unique(cube_nat_level$iso3) : object 'cube_nat_level' not found

Here is the line of code

https://github.com/bertozzivill/map-itn-cube/blob/master/itn_cube/shiny_proto/app.r#L25

Indeed I cannot see the object definition.

Camilo V.

**Comment by bertozzivill** [comment]
Thanks for catching this @cavargasru! That line was included by mistake and is not needed, just pushed a version that omits it.
